### ISSUE TITLE
Comunication between server and client

### ISSUE THREAD

**Issue by denon2002** [multunus/onemdm-server#5]
Hy,

How to communicate the server with the customers?
Which ports I need to open up for communication.

**Comment by leenasn** [comment]
The server runs on port 3000.  I am not sure whether your questions is on that. Can you explain in detail what you meant by customers? Are you referring to the Android devices?

**Comment by denon2002** [comment]
ok it works. the most mdm server have a separately port for the enrollment. your server need only the port 3000.

How i can start the enrollment process manually in the app?

**Comment by denon2002** [comment]
When I start the app on my mobile, I get the following info in the console of the server.

[2016-10-11 14:25:23] ERROR bad Request-Line `\x16\x03\x01\x00▒\x01\x00\x00▒\x03\x03▒▒▒.I▒▒Z▒H▒͸▒\x03;<▒\x18▒Y▒Uh▒hZ▒\t▒▒\x12\x00\x00,▒+▒,▒/▒0\x00▒\x00▒▒\t▒'.
[2016-10-11 14:25:23] ERROR bad Request-Line `\x16\x03\x00\x00I\x01\x00\x00E\x03\x00▒-▒8▒▒x▒+f>KJɑE▒i▒▒\x11▒s r▒a▒|▒O\x18\x00\x00\x1E▒\t▒'.

**Comment by leenasn** [comment]
I am not sure what the error is. Most likely it might be with the locale. I am not sure whether the problem is at the server end of at the device end.  If you can share more lines from the log file, it might be useful. 

Have you tried [installing our demo app](https://s3.amazonaws.com/onemdm-demo/demo-onemdm.apk)? If not, can you install it and see whether it works fine on the same device? 

You can also try connecting to our demo app from the android app too. Change the HOST_URL to https://demo-onemdm.herokuapp.com/ in Config.java and run the app. 

You can log onto the admin console of the demo app as the instructions given below, to check whether your device has been registered or not.

The instructions for http://multunus.github.io/onemdm-server/#live-demo

**Comment by denon2002** [comment]
Hy, Demo APK is running with yours Server. I think the create APK is faulty.
Can you create a APK with a menu bar,  where I can enter my server url in this APP ?

**Comment by leenasn** [comment]
@denon2002 sorry for the late response. 

Can you share your server URL so that I can generate it and send it back to you? This might be faster than changing the UI.
