### ISSUE TITLE
App Install

### ISSUE THREAD

**Issue by grego1981** [multunus/onemdm-server#9]
I've started using the server the last few days and I have some questions not covered in the instructions:
 - I have added an app and tried to push it, but where to you place the apk files? 
 - Does the application reports the already installed apps? 
 - On the devices I have tested no IMEI is diplayed. Do I need to configure something more?
 - At every heartbeat I get "Can't verify CSRF token authenticity" do I need to change something?

Thank you!

**Comment by leenasn** [comment]
@grego1981 Answering your questions:

- Currently the app only supports installing apps from the playstore. You can give a package name, and then it installs the same from the PlayStore. 
- It doesn't report the installed apps. 
- From Android 6.0 version onwards, the API for reading the IMEI had removed. So that might be the reason its not displaying the IMEI number
- The warning is fine about heartbeat. You can ignore the same.
